#Application URL
old_url = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url=http://localhost/orangehrm/web/index.php/auth/login

#Browser Configuration
browser = chrome

#Credentials
old_username = admin
old_password = admin123
username = test_gupta
password = Stupid1!Password

#Implicitwait (in seconds)
implicitwait = 30

#Action Driver Wait
actiondriverwait = 30